fix attrerror in some invocations of script cmd+
Closes #70. Addresses a condition in this extparser and some others
where the invocations action needs to be specified along with some
value for nargs and it was not. For later reference, errors here
occur in InvocationsAction and look like:

AttributeError: 'str' object has no attribute 'first_spid'